import { type NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";

import { trpc } from "../utils/trpc";
import { css } from "goober";
import { motion } from "framer-motion";
import { forwardRef, LegacyRef, MutableRefObject, useRef } from "react";
import PlayingCard from "../components/PlayingCard/PlayingCard";

const Home: NextPage = () => {
  const hello = trpc.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Bubbles</title>
        <meta
          name="Bubbles: Cooperative Card Game"
          content="Generated by create-t3-app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <div className="min-h-screen bg-[url('/space-bg.webp')] bg-cover bg-no-repeat">
          <Hand cards={[{ value: 1 }, { value: 2 }, { value: 3 }]} />
        </div>
      </main>
    </>
  );
};

export default Home;
interface Props {
  cards: Array<Parameters<typeof PlayingCard>[0]>;
}
function Hand({ cards, ...otherProps }: Props) {
  const playingField = useRef<HTMLDivElement | null>(null);

  console.log("playingField", playingField.current);

  const x = playingField ? playingField.current?.offsetLeft : 300;
  const y = playingField ? playingField.current?.offsetTop : 300;
  console.log({ x, y });
  return (
    <>
      <div className="h-48 w-48"></div>
      <div {...otherProps} className={styles.hand}>
        {cards.map((card, index) => (
          <motion.div
            key={index}
            className={styles.card}
            whileHover={{
              translateY: -24,
            }}
            initial={{ opacity: 0, x: 0, y: 448 / 2 }}
            animate={{ opacity: 1, x: 0, y: 0 }}
            transition={{ duration: 2 }}
            drag
            dragSnapToOrigin
            onDrop={(e) => console.log(e)}
            onDragEnd={(e) => console.log(e)}
          >
            <PlayingCard value={card.value} />
          </motion.div>
        ))}
      </div>
      <PlayingField ref={playingField} />
    </>
  );
}

interface PlayingFieldProps {}
const PlayingField = forwardRef<HTMLDivElement, PlayingFieldProps>(
  (PlayingFieldProps, ref) => {
    return (
      <div ref={ref} className="h-64 w-48 rounded-md border border-white"></div>
    );
  }
);

const styles = {
  hand: css({ display: "flex" }),
  card: css({}),
};
const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = trpc.auth.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined }
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => signOut() : () => signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
};
